#!/bin/sh

if [ `id -u` -ne 0 ]
then
    echo Please enter your password to continue the install with root privleges.
    sudo "$0"
    exit
fi

BIN_DIR=`dirname "$0"`
if [ "$BIN_DIR" = "." ]
then
	BIN_DIR=`pwd`
fi

TOP_SOURCE_DIST_DIR=`dirname "$BIN_DIR"`

# Get PREFIX, INSTALL_BIN_DIR, MACRO_INSTALL_DIR
. "$BIN_DIR"/config.sh

install -d "$INSTALL_BIN_DIR"
install -d "$MACRO_INSTALL_DIR"

if [ `uname -s` = 'SunOS' ]
then
	# Call stupid Solaris installer. It writes its own output.
	install -f "$INSTALL_BIN_DIR" "$TOP_SOURCE_DIST_DIR"/Source/merlin32
	for MACRO_FILE in "$TOP_SOURCE_DIST_DIR"/Library/*
	do
		install -f "$MACRO_INSTALL_DIR" "$MACRO_FILE"
	done
else
	# Call non-stupid installer
	echo Installing merlin32 to $INSTALL_BIN_DIR
	install "$TOP_SOURCE_DIST_DIR"/Source/merlin32 "$INSTALL_BIN_DIR"
	echo Installing library files to $MACRO_INSTALL_DIR
	install "$TOP_SOURCE_DIST_DIR"/Library/* "$MACRO_INSTALL_DIR"
fi

